Adding flag to skip rounding to the hour
danielfernau/unifi-protect-video-downloader pull request #376
Opened 2023-11-09 17:56 UTC by heschlie

Adds `--skip-round-to-hour`

This leaves the default functionality in place but adds a new flag to skip rounding the clips to the hour(ish)

fixes: #34 #57 

I know that the UI can download a time range but for me if that clip is more than ~1m it crashes, it also frequently crashes when scanning over footage, so this is easier/more reliable.

2023-11-11 16:54 UTC, danielfernau requested changes
Looks good to me, thanks a lot for your contribution!

Change requests are only style-related to make the [`black` code formatter](https://github.com/psf/black) happy :)

2023-11-11 16:54 UTC, danielfernau commented on protect_archiver/cli/download.py
> +    help="Skips rounding the clips to hour markers."
```suggestion
    help="Skips rounding the clips to hour markers.",
```

2023-11-11 16:54 UTC, danielfernau commented on protect_archiver/downloader/__init__.py
> +    def download_footage(client: Any, start: datetime, end: datetime, camera: Any, skip_round_to_hour: bool) -> Any:
```suggestion
    def download_footage(
        client: Any, start: datetime, end: datetime, camera: Any, skip_round_to_hour: bool
    ) -> Any:
```

2023-11-11 16:54 UTC, danielfernau commented on protect_archiver/downloader/download_footage.py
> +def download_footage(client: Any, start: datetime, end: datetime, camera: Camera, skip_round_to_hour: bool) -> None:
```suggestion
def download_footage(
    client: Any, start: datetime, end: datetime, camera: Camera, skip_round_to_hour: bool
) -> None:
```

2023-11-14 04:29 UTC, heschlie commented
So the linter is unhappy about the `List` -> `Iterable` but in this scenario the typing _should_ be fine so I asked the linter to ignore it. If preferred I can convert the initial declaration of `intervals` to:

```python
intervals = (for x in x [( start, end)])
```

Which returns a `Generator` to match the `yields` from the call to `calculate_intervals()`

2023-11-15 21:40 UTC, danielfernau commented
Just had another look at it, a bit less tired this time :)
The way you've implemented it here, the option doesn't just disable the hour rounding; it disables the generator function in general. However, the generator function is needed to split the downloads into 1-hour segments if more than one hour is being downloaded. Otherwise, you risk the Protect console crashing when asking for more than 1 hour of footage at a time.

The way I'd implement it would be to add two options to the generator itself: one that disables the alignment to absolute hours while keeping the 1-hour segment splitting, and a second one that disables the interval generator entirely and returns start and end unchanged (but comes with a warning that this might cause issues/crashes). This, along with some improvements to the generator algorithm itself, should solve the open issues, including your use-case. I've already started experimenting a bit, making good progress so far, and will continue tomorrow. I'll keep you updated. Thanks again for your patience, suggestions and support!

2023-11-21 22:53 UTC, closed without merging

2023-11-21 22:59 UTC, danielfernau commented
Hi @heschlie!

I've just added the requested feature flags (`--disable-alignment`, `--disable-splitting`) and also fixed some inconsistencies in the calculations. I'll publish a new version of the tool soon; for now you can use the ':edge' tag of the Docker image to have access to the new features.

Thanks again for your contribution, feel free to suggest additional improvements any time 👍